### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by odinho** [dcramer/logan#26]
I started investigating some faults, wanted to fix, then I came here and saw I had already investigated this before and done a pull request all the way back in May.

This has not been merged and a new release has not been put up on pypi.

Is this project dead?
Why is that so?
Do you want someone else to take over maintainership?  I could do that, though I'd mostly maintain, not develop.

Hope everything is OK and there's not worse reasons for project being stale.

**Comment by dcramer** [comment]
Semi-dead. I'll add you as maintainer.

We no longer use it in Sentry because we brought it all in-house to the codebase to make it easier to manage/change. It was easier/more stable than constantly trying to add features to Logan.

**Comment by odinho** [comment]
Heh, thanks. :)

Okay, I saw that change at Sentry, guess it makes sense for such a big project.

Could you add me on pypi?  "velmont.no" is my username there it seems.

**Comment by dcramer** [comment]
All set
